### ISSUE TITLE
doesn't work as of 4/18/2023 Firefox Dev Edition 

### ISSUE THREAD

**Issue by cybector** [Claudiohbsantos/github-material-icons-extension#62] opened 2023-04-18 19:48 UTC
![image](https://user-images.githubusercontent.com/63419902/232889142-72254ab9-8ddc-402d-8a43-a57a3934fea3.png)

**Comment by AdamRaichu** [comment] 2023-04-18 20:01
This is a duplicate of #55.

**Comment by AdamRaichu** [comment] 2023-04-18 20:05
Np.

This issue can be closed.

**Comment by Claudiohbsantos** [comment] 2023-04-27 04:14
Thanks! Yeah, I just merged the PR that implements support for the new code view, should be available in the next version of the extension

**Closed by Claudiohbsantos** 2023-04-27 04:14 UTC
