### ISSUE TITLE
icon not showing in new project tree

### ISSUE THREAD

**Issue by fbec76** [Claudiohbsantos/github-material-icons-extension#61] opened 2023-04-18 15:32 UTC
When using the new project tree the icons won't be placed.
Actually, the new project tree where your project is expandable on the left doesn't have any icons.

Example for this project itself:
![image](https://user-images.githubusercontent.com/37416552/232827546-8a7ef602-0db4-470a-bc1a-54ca0a595be6.png)

**Comment by AdamRaichu** [comment] 2023-04-18 16:23
This is a duplicate of #55.

**Closed** 2023-04-18 16:24 UTC
